# Generated by Django 6.0.7 on 2026-07-07 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('categoria', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red')], max_length=20, verbose_name='Categoria')),
                ('condiciones', models.JSONField(default=dict, verbose_name='Condiciones (JSON)')),
                ('conclusion', models.CharField(max_length=100, verbose_name='Conclusion')),
                ('acciones', models.JSONField(default=list, verbose_name='Acciones recomendadas')),
                ('explicacion', models.TextField(blank=True, verbose_name='Explicacion')),
                ('prioridad', models.IntegerField(default=10, verbose_name='Prioridad (menor = mayor prioridad)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='SesionDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Clave de sesion')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Datos de la sesion')),
                ('reglas_aplicadas', models.JSONField(blank=True, default=list, verbose_name='Reglas aplicadas')),
                ('preguntas_realizadas', models.JSONField(blank=True, default=list, verbose_name='Preguntas realizadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sesion de diagnostico',
                'verbose_name_plural': 'Sesiones de diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de sesion')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='en_curso', max_length=20, verbose_name='Estado')),
                ('sintomas', models.JSONField(blank=True, default=dict, verbose_name='Sintomas reportados')),
                ('diagnostico_final', models.TextField(blank=True, null=True, verbose_name='Diagnostico final')),
                ('falla_encontrada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Falla encontrada')),
                ('recomendaciones', models.JSONField(blank=True, default=list, verbose_name='Recomendaciones')),
                ('reglas_aplicadas', models.JSONField(blank=True, default=list, verbose_name='Reglas aplicadas')),
                ('confianza', models.IntegerField(default=0, verbose_name='Nivel de confianza (%)')),
                ('tiempo_respuesta', models.FloatField(default=0, verbose_name='Tiempo de respuesta (segundos)')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del usuario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
